### PR TITLE
Modal window

### PR DESCRIPTION
**Pull request by 6**
- creates a reusable modal service/component. It auto-centers on the screen and remains centered while you resize the window.
- clicking on the modal backdrop or hitting Esc key will dismiss the modal
- updates `./server` script to force browser not to cache files it's serving.

I ended up running into issues with the jQuery plugin, so decided to just create my own modal:

screen shot 2017-06-08 at 9 17 29 pm
screen shot 2017-06-08 at 9 17 33 pm

To use it, just inject the `wsModalService` into your controller, and add the following code:
screen shot 2017-06-08 at 9 19 51 pm

### CODE REVIEW

**Comment by 6** [comment]
A couple of non-critical enhancements I'd like to do at some point:

- I was having a lot of trouble getting `$animate.leave` to work when closing the modal. It the callback was being called the first time, but not subsequent times.
- It would be nice to have `ladda-button` working with this, but not sure of the best way to do that.

**Comment by 6** [comment]
screenshot of it in use on logged in site, 
screen shot 2017-06-08 at 11 32 17 pm

**Comment by 6** [comment]
feedback appreciated and happy to create a subsequent PR to address anything.

**Comment by benjyblack** [comment]
Very cool!! Excited to use this

**Comment by mondayrain** [comment]
yaaaaaaas!

**Pull request merged**
