### PR TITLE
Add missing polyfills for ES6 features

### PR DESCRIPTION
**Pull request by SethDavenport**
IE 9, 10, 11 are missing a bunch of stuff from that ES6 users take for granted. Updating to later dependencies (especially autonumeric) has revealed a hidden dependency on this stuff.

### CODE REVIEW

**Comment by 6** [comment]
just wondering, how much does this increase the overall size of the package?

**Comment by SethDavenport** [comment]
Without polyfills: ws-directives.js    240 kB
With polyfills:       ws-directives.js    271 kB

So it does add a little.

screen shot 2017-08-10 at 9 53 10 am

**Comment by SethDavenport** [comment]
I could prune it down to just add `import 'core-js/es6/array';` which would result in a size of 246 kB.  That would fix the observed bugsnag issue for IE11 specifically.  We'd have to keep an eye out for any other IE errors and fix them on a case-by case basis.

**Comment by SethDavenport** [comment]
Do we have browser stats anywhere?

**Comment by 6** [comment]
Some discussion from July 2016 (a bit over a year ago) at https://wealthsimple.slack.com/archives/C1AB5KPUH/p1468282641000953

- 6% of our overall visitors use some version of IE
- 90% of those IE users were on the latest IE 11

@nickmwhite can probably pull more recent stats from Google Analytics, although I'd guess that the share of IE users has probably decreased

**Pull request merged**
