### PR TITLE
Add the option for checkboxes in a modal

### PR DESCRIPTION
**Pull request by abejfehr**
Adds the option for a checkbox to the modal component. 

Required in a special case.

modal-checkbox
Sorry for the slow gif, it was recorded at 60fps but after removing an incriminating frame from it macOS preview saved it at 30fps again.

### CODE REVIEW

**Comment by abejfehr** [comment]
Upon trying to make a screenshot, which was going to be animated, I realized that the checkbox wasn't working properly. After spending much too long trying to figure out how this works, I'm going to just give up. If you have time tomorrow morning @benjyblack I'd like some help with this

**Comment by benjyblack** [comment]
Another possible solution.

Put an ng-form somewhere in the modal directive, and then disable/enable the Okay button based on whether that form is valid.

Then, in the HTML string you send in, have another ng-form that is invalid if the user has not checked the checkbox.

Since parent forms in Angular are invalid if any of their nested forms are invalid, this will work.

**Comment by abejfehr** [comment]
@DanGodfrey I added you to this PR as my Dev Manager of choice and @SethDavenport, it was @benjyblack's suggestion to add you to check over this PR as well and see if you had any ideas for improvement (which I may or may not be able to implement due to time constraints)

**Comment by benjyblack** [comment]
I gave it a quick go with my suggested solution. It didn't go quite as smoothly as expected. The problem is that content you supply with `ng-bind-html` doesn't get `$compile`'d with the parent scope. Not sure what the best way to get around this is.

**Comment by SethDavenport** [comment]
This modal implementation is interesting (although the 'interestingness' pre-dates this PR). I'm not super comfortable with the `$sce.trustAsHtml` stuff but I'm probably missing context.  I would probably have been inclined to go with a solution based on transclusion if you want HTML in the body.

That said, the specific changes in this PR seem fine; I'm not seeing anything obvious as to why it won't work. @abejfehr do you have a branch where this is being used? I can check it out and poke at it.

**Comment by abejfehr** [comment]
@SethDavenport transclusion would be _amazing_, right now I have HTML in a string which just looks nasty.

I'm just making a commit and I'll DM you the terminal branch name after.

**Comment by abejfehr** [comment]
@DanGodfrey duly noted! I'll merge this PR for now

**Pull request merged**
