### PR TITLE
Bind HTML to ws-content-selector blurb

### PR DESCRIPTION
**Pull request by evancloutier**
Introduces `valueBlurb` within the content-selector. This will allow us to display account values like so:

screen shot 2017-11-17 at 3 39 30 pm
screen shot 2017-11-17 at 3 39 36 pm

### CODE REVIEW

**Comment by DanGodfrey** [comment]
@SethDavenport has some opinions on this and is looking to put in some new best practices around this kind of thing.

**Comment by evancloutier** [comment]
Sounds good to me - I'll wait for his input to move forward with this. In the meantime, I'll just `npm link` locally.

**Comment by f3ndot** [comment]
From a security perspective, this can only be ok if the variable only contains content that we have explicitly provided: no user-supplied content like their name or email.

**Comment by evancloutier** [comment]
@f3ndot We are providing the content.

**Comment by SethDavenport** [comment]
Yeah re: opinions: I don't like bind html at all.  The context may be fine now but it's still not the best practice.

**Comment by SethDavenport** [comment]
Let's see if we can do something like this with transclusion instead

**Pull request merged**
